import {StyleSheet} from 'react-native';
import Colors from '../../constants/Colors';
import Sizes from '../../constants/Sizes';

const styles = StyleSheet.create({
  root: {
    backgroundColor: 'transparent',
    minHeight: Sizes.hp('86%'),
  },
  box_card_wrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: Sizes.wp('2%'),
    marginVertical: Sizes.hp('3%'),
  },
  box: {
    height: Sizes.hp('10%'),
    width: Sizes.wp('20%'),
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
  },
  box_image: {
    height: Sizes.hp('10%'),
    width: Sizes.wp('10%'),
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  naviContainer: {
    height: Sizes.hp('15%'),
    width: Sizes.wp('22%'),
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: 'center',
  },
  iconContainer: {
    height: Sizes.hp('6%'),
    width: Sizes.wp('12%'),
    borderColor: Colors.borderColor,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: Colors.white,
  },
  box_tittle: {
    fontSize: 12,
    textAlign: 'center',
    fontWeight: 'bold',
    color: Colors.TEXT1,
  },
  box_root: {
    marginVertical: 5,
    justifyContent: 'center',
    height: Sizes.hp('12%'),
    width: Sizes.wp('25%'),
    alignItems: 'center',
  },
  box_root1: {
    marginVertical: 5,
    justifyContent: 'center',
    height: Sizes.hp('12%'),
    width: Sizes.wp('25%'),
    alignItems: 'center',
  },
  navigation_box: {
    width: Sizes.wp('94%'),
    height: Sizes.hp('8%'),
    justifyContent: 'center',
    alignSelf: 'center',
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: '#3D398915',
    borderColor: '#3D398930',
    marginVertical: 5,
  },
  navigation_box_text: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.TEXT1,
    marginLeft: Sizes.wp('5%'),
  },
  birthday_icon: {
    height: Sizes.hp('5%'),
    width: Sizes.wp('10%'),
    marginLeft: Sizes.wp('2%'),
  },
  navigation_box_content: {flex: 1, flexDirection: 'row', alignItems: 'center'},
  uploadpic_container: {
    // height: Sizes.hp('23%'),
    width: Sizes.wp('94%'),
    alignSelf: 'center',
    marginVertical: 10,
  },
  uploadpic_container_headerText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.TEXT1,
  },
  uploadpic_container_viewText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.PRIMARY,
    fontStyle: 'italic',
  },
  uploadpic_container_image_view: {
    height: Sizes.hp('15%'),
    width: Sizes.wp('30%'),
    marginHorizontal: 5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.borderColor,
    justifyContent: 'center',
    marginVertical: 5,
  },
  uploadpic_container_image: {
    height: Sizes.hp('15%'),
    width: Sizes.wp('30%'),
    resizeMode: 'cover',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.borderColor,
  },
  uploadpic_container_dateview: {
    height: Sizes.hp('2%'),
    width: Sizes.wp('15%'),
    backgroundColor: Colors.PRIMARY,
    zIndex: 1,
    position: 'absolute',
    top: 12,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
  },
  uploadpic_container_eventview: {
    zIndex: 1,
    // position: 'absolute',
    // bottom: 0,
    // marginVertical: -2,
  },
  uploadpic_container_date: {
    fontSize: 12,
    fontWeight: '400',
    color: Colors.white,
    textAlign: 'center',
    height: Sizes.hp('2%'),
  },
  uploadpic_container_eventname: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.TEXT1,
    textAlign: 'center',
    alignSelf: 'center',
  },

  // moti container styles
  container: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    backgroundColor: Colors.transparent,
    // flexDirection: 'row',
  },
  skeletonText: {
    marginTop: 10,
    width: '90%',
    height: 20,
    backgroundColor: '#f5f5f5',
    borderRadius: 10,
  },
});

export default styles;
