import Colors from '../../constants/Colors';
import Sizes from '../../constants/Sizes';

const {StyleSheet} = require('react-native');

const styles = StyleSheet.create({
  root: {
    // flexGrow: 1,
    backgroundColor: Colors.transparent,
  },
  noEventsText: {
    fontSize: 16,
    color: Colors.TEXT1,
    textAlign: 'center',
  },
  image_wrap: {
    alignItems: 'center',
    marginTop: 20,
  },
  container: {
    flex: 1,
    backgroundColor: Colors.Background,
    justifyContent: 'center',
    margin: 10,
    marginBottom: 200,
  },
  today_carousel: {
    alignSelf: 'center',
    flex: 1,
  },
  title: {
    // flex: 1,
    fontSize: 15,
    fontWeight: '500',
    color: Colors.TEXT1,
    paddingHorizontal: 10,
    marginVertical: 2,
  },
  Labeltitle: {
    marginTop: 10,
    paddingHorizontal: 10,
    fontSize: 15,
    fontWeight: '500',
    color: Colors.TEXT1,
  },
  textInputField: {
    width: '95%',
    marginTop: 5,
    alignSelf: 'center',
  },
  date_container: {
    width: '100%',
    marginTop: 5,
    alignSelf: 'center',
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    backgroundColor: Colors.white,
    flexDirection: 'row',
    borderColor: Colors.PRIMARY,
    justifyContent: 'space-between',
  },
  placeHolder: {
    color: Colors.TEXT1,
    fontSize: 15,
    fontWeight: '300',
    fontStyle: 'italic',
  },
  photo_container: {
    flex: 1,
    width: '95%',
    height: Sizes.hp('20%'),
    backgroundColor: '#3D398910',
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 10,
    borderColor: 'grey',
    marginVertical: 5,
  },
  photo_button_container: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: Colors.PRIMARY,
    padding: 10,
  },
  photo_button_text: {
    color: Colors.PRIMARY,
    fontSize: 15,
    fontWeight: '500',
  },

  image: {
    flex: 1,
    width: Sizes.wp('20%'),
    height: Sizes.hp('10%'),
    backgroundColor: '#3D398910',
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 50,
    borderColor: 'grey',
    marginVertical: 5,
  },
  textsms_container: {
    width: Sizes.wp('95%'),
    alignSelf: 'center',
    borderWidth: 1,
    borderRadius: 10,
    borderColor: Colors.TEXT1,
  },
  textsms_view: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
  },
  textsms_option_border: {
    flexDirection: 'row',
    gap: 10,
    padding: 10,
    alignItems: 'center',
  },
  textsms_text: {
    fontSize: 15,
    color: Colors.TEXT1,
    fontWeight: '500',
  },
  //create post
  container_textsms: {
    flexDirection: 'row',
    paddingHorizontal: 10,
  },
  view_container: {
    flex: 1,
    flexDirection: 'row',
    width: Sizes.wp('95%'),
    alignSelf: 'center',
    alignItems: 'center',
  },
  cardContainer: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderRadius: 10,
    width: Sizes.wp('95%'),
    alignSelf: 'center',
    padding: 10,
    borderColor: Colors.borderColor,
  },
  // event details style
  event_detail_container: {
    // flex: 0.51,
    width: Sizes.wp('95%'),
    alignSelf: 'center',
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    borderColor: Colors.borderColor,
    marginVertical: 10,
    elevation: 5,
  },
  profilePic: {
    width: Sizes.wp('30%'),
    height: Sizes.hp('15%'),
    borderRadius: 70,
    alignSelf: 'center',
  },
  profilePicMarriage: {
    width: Sizes.wp('20%'),
    height: Sizes.hp('10%'),
    borderRadius: 70,
    alignSelf: 'center',
  },
  event_details_container_title: {
    fontSize: 20,
    fontWeight: '500',
    color: Colors.PRIMARY,
    textAlign: 'center',
    marginTop: 10,
  },
  event_details_container_date: {
    fontSize: 14,
    fontWeight: '300',
    color: Colors.TEXT1,
    alignSelf: 'center',
  },
  rootTemplatedContainer: {
    width: Sizes.wp('95%'),
    backgroundColor: Colors.white,
    alignSelf: 'center',
    height: Sizes.hp('10%'),
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    borderColor: Colors.borderColor,
    marginVertical: 10,
    elevation: 5,
    bottom: 300,
  },
  templet: {
    width: Sizes.wp('95%'),
    backgroundColor: Colors.white,
    alignSelf: 'center',
    height: Sizes.hp('10%'),
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    borderColor: Colors.borderColor,
    marginVertical: 10,
    elevation: 5,
  },
});

export default styles;
