export default {
  //Navigator Screen Name
  ATUH_NAVIGATOR: 'AuthNavigator',
  BOTOOM_TAB_NAVIGATOR: 'BottomTabNavigator',
  CURVED_BOTTOM_TAB_NAVIGATOR: 'CurvedBottomTabNavigator',
  DRWAER_NAVIGATOR: 'DrawerStack',
  ADD_NAVIGATOR: 'AddNavigator',
  MAIN_NAVIGATOR: 'leftDrawer',

  //Navigator in the Screen Name
  PHOTO_NAVIGATOR: 'PhotoNavigator',
  //Screen Name
  SPLASH: 'Splash',
  ONBOARDING: 'OnBoarding',
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  FORGET_PASSWORD: 'Forget-Password',
  CHANGE_PASSWORD: 'Change-Password',
  VERIFY_OTP: 'VerifyOTP',
  HOME: 'Home',
  PROFILE: 'Profile',
  ADD: 'Add',
  PHOTOS_STATUS: 'PhotoStatus',
  EVENTS: 'Events',
  WALLPAPER: 'Wallpaper',
  TERM_AND_CONDITION: 'TermAndCondtion',
  BIRTHDAY_REMAINDER_NAVIGATOR: 'BirthdayRemainderNavigator',
  MY_BUSSINESS: 'MyBussinessNavigator',
  LANGUAGE_SELECTION: 'LanguageSelection',
  MY_POST: 'MyPost',
  CHOOSE: 'Choose',
  TUTORIALS: 'Tutorial',
  Privacy_Policy: 'Privacy',
  FEEDBACK: 'FeedBack',
  HELPSUPPORT: 'HelpSupport',
  NOTIFICATION: 'Notification',
  AI_IMAGE: 'Ai-image',

  // work profile
  WORK_PROFILE_NAVIGATOR: 'WorkProfileNavigator',
  WORK_PROFILE_LIST: 'WorkProfileList',
  SELECT_WORK_PROFILE: 'SelectWork Profile',
  ADD_EDIT_BUSINESS_STEP1: 'AddEditBusinessStep1',
  ADD_EDIT_BUSINESS_STEP2: 'AddEditBusinessStep2',
  ADD_EDIT_POLITICAL: 'AddEditPolitical',
  ADD_POLITICAL_PROFILE: 'AddPoliticalProfile',
  ADD_LEADER_IN_POLITICAL_PROFILE: 'AddLeaderInPoliticalProfile',
};
